### ISSUE TITLE
Display compiler warnings/errors back to the user

### ISSUE THREAD

**Issue by ivaylohristakiev** [ivaylohristakiev/GP2-editor#24]

**Comment by Rulerx** [comment]
The proper Fail result is now displayed as a pop-up message box.

**Comment by ivaylohristakiev** [comment]
The proper Fail result is now displayed as a pop-up message box.

**Comment by ivaylohristakiev** [comment]
The messages the Editor is listening for:

- During validation - "is valid" and "is invalid" for validation of rules/programs/graphs using -v flag
- During Compilation - output contains "Generating program code" for successful compilation 
   Note: Does not catch seg faults 
- During running - output contains "error"
